name: New Tag Created

on:
  push:
    tags:
      - "**"

jobs:
  test_on_tag:
    uses: ./.github/workflows/push.yaml
  
  create_release_draft:
    runs-on: ubuntu-latest
    needs: [ test_on_tag ]
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: gh release create "$TAG" --title="$TAG" --draft
  
  build_docker_image:
    runs-on: ubuntu-latest
    needs: [ test_on_tag ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Setup Docker QEMU Emulation
        uses: docker/setup-qemu-action@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: amieldelatorre/myip:${{ github.ref_name }},amieldelatorre/myip:latest
  
  publish-release:
    needs: [ create_release_draft, build_docker_image ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: gh release edit "$TAG" --draft=false
    
        
    
    
    
    